name: Go Test

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'  # Change to your Go version if different

    - name: Run tests
      run: |
        go test -v ./...
